# Generated by Django 4.0.3 on 2023-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
